# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane
setup_travis

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :tests do
    run_tests(scheme: "bumpy",
              devices: ["iPhone X"])
  end
end
