# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_travis
    clear_derived_data
  end


  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "bumpy",
      devices: ["iPhone X"],
      code_coverage: true
    )
    xcov(
      workspace: "bumpy.xcworkspace",
      scheme: "bumpy",
      output_directory: "xcov_output"
    )
  end
end
